version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: base
    ports:
      - 5432:5432